tabs:
    fields:
        site_name:
            label: ln.site_name
            default:  D-pot Theme
            span: left
            tab: ln.general

        site_description:
            label: ln.site_description
            default:  D-pot Theme for October CMS
            span: full
            tab: ln.general

        site_logo:
            label: ln.site_logo
            type: mediafinder
            mode: image
            default: assets/images/logo.png
            imageWidth: 240
            imageHeight: 90
            maxItems: 1
            span: left
            tab: ln.general

        site_maintenance_message:
            label: ln.site_maintenance_message
            default:  The Site is in Maintenance
            span: full
            tab: ln.general

        # Banner Section
        banner_active:
            type: switch
            label: ln.banner_active
            default: true
            tab: ln.banner

        banner_title:
            label: ln.banner_title
            default:  Take care my dog
            span: left
            tab: ln.banner

        banner_description:
            type: textarea
            label: ln.banner_description
            default: consectetur adipiscing elit, sed do eiusmod tempor incidid
            size: small
            span: left
            tab: ln.banner

        banner_image:
            label: ln.banner_image
            type: mediafinder
            mode: image
            default: assets/images/banner.jpg
            imageWidth: 1200
            imageHeight: 600
            maxItems: 1
            span: left
            tab: ln.banner
        # Banner Section

        # About Section
        about_active:
            type: switch
            label: ln.about_active
            default: true
            tab: ln.about

        about_title:
            type: text
            label: ln.about_title
            default: About Dogs
            span: left
            tab: ln.about

        about_description:
            type: textarea
            label: ln.about_description
            default:
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
                Tempora quis, repellendus dolore explicabo incidunt dicta aperiam quasi.
            size: small
            span: left
            tab: ln.about

        about_image:
            label: ln.about_image
            type: mediafinder
            mode: image
            default: assets/images/about-img.jpg
            imageWidth: 1200
            imageHeight: 600
            maxItems: 1
            span: left
            tab: ln.about
        # About Section

        # Gallery Section
        gallery_active:
            type: switch
            label: ln.gallery_active
            default: true
            tab: ln.gallery

        gallery_title:
            type: text
            label: ln.gallery_title
            default: Our Dogs
            span: left
            tab: ln.gallery

        gallery_description:
            type: textarea
            label: ln.gallery_description
            default:
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
                Tempora quis, repellendus dolore explicabo incidunt dicta aperiam quasi, 
                impedit necessitatibus asperiores fugiat at quisquam natus commodi quas doloremque dolores doloribus labore?
            size: small
            span: left
            tab: ln.gallery

        gallery_images:
            type: repeater
            form:
                fields:
                    image:
                        label: Image
                        comment: gallery_images.select
                        type: mediafinder
                        mode: image
                        imageWidth: 600
                        imageHeight: 300
                        maxItems: 6
            tab: ln.gallery
        # Gallery Section

        # Adoption Section
        adoption_active:
            type: switch
            label: ln.adoption_active
            default: true
            tab: ln.adoption

        adoption_title:
            type: text
            label: ln.adoption_title
            default: Pet adoption be part of something beautiful
            span: left
            tab: ln.adoption

        adoption_description:
            type: textarea
            label: ln.adoption_description
            default:
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. 
                Tempora quis, repellendus dolore explicabo incidunt dicta aperiam quasi, 
                impedit necessitatibus asperiores fugiat at quisquam natus commodi quas doloremque dolores doloribus labore?
            size: small
            span: left
            tab: ln.adoption

        adoption_image:
            label: ln.adoption_image
            comment: Select an image
            default: assets/images/dog-img.png
            type: mediafinder
            mode: image
            imageWidth: 350
            imageHeight: 700
            maxItems: 1
            span: left
            tab: ln.adoption
        # Adoption Section

        # Contact Section
        contact_active:
            type: switch
            label: ln.contact_active
            default: true
            tab: ln.contact
        # Contact Section

        # Newsletter Section
        newsletter_active:
            type: switch
            label: ln.newsletter_active
            default: true
            tab: ln.newsletter
        # Newsletter Section

        # Footer Section
        footer_active:
            type: switch
            label: ln.footer_active
            default: true
            tab: ln.footer

        footer_address:
            type: text
            label: ln.footer_address
            default: Gb road 123 london Uk
            span: left
            tab: ln.footer

        footer_phone:
            type: text
            label: ln.footer_phone
            default: (+71) 9876543210
            span: left
            tab: ln.footer

        footer_email:
            type: text
            label: ln.footer_email
            default: alexhenriquepv@gmail.com
            span: left
            tab: ln.footer

        # Menu Section
        menu_active:
            type: switch
            label: ln.menu_active
            default: true
            tab: ln.menu

        menu_items:
            type: repeater
            form:
                fields:
                    label:
                        type: Text
                        label: ln.menu_label
                        default: New Menu
                        span: left
                    url:
                        type: text
                        label: ln.menu_url
                        default: /
                        span: right
            tab: ln.menu
